config/routes.rb
PaddleSportsNorthAmerica::Application.routes.draw do

  get "coaches/index"

  root :to => "home#landing"

  get 'home' => "home#index"
  get 'about' => "home#about"
  
  get 'calendar' => "calendar#index", as: :calendar

  #get 'coaches' => "home#paddlers"
  get 'coaches' => "coaches#index"
  get 'documents' => "home#documents"
  get 'guidance' => "home#guidance"
  get 'membership' => "home#membership"
  
  get 'about/candidates' => "home#candidates"

  get 'contact' => "contact#index"
  post 'contact' => "contact#index"
  get 'contact/thank-you' => "contact#thank_you"

  # Active Admin has poor support for polymorphic relationships
  # so we have to declare our routes manually

  namespace :admin do
    get 'members/autocomplete' => 'members#autocomplete'
    # get '', to: 'dashboard#index', as: '/' 
    resources :members do
      resources :addresses
      resources :phone_numbers
      resources :email_addresses

      resources :memberships do
        get 'print' => 'memberships#print'
      end

      resources :qualifications do
        get 'print' => 'qualifications#print'
      end

    end

    resources :centers do
      resources :addresses
      resources :phone_numbers
      resources :email_addresses
    end

    get 'products/autocomplete' => 'products#autocomplete'
  end

  # begin
    ActiveAdmin.routes(self)
  # rescue
    # Rails.logger.warn "Failed to initialize aa routes"
  # end

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h4>Keep in Touch</h4>
        <p>Sign up for the PNA newsletter to stay up to date on important news and events.</p>
        <form>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Email">
            <span class="input-group-btn">
              <button class="btn btn-success" type="button"><span class="glyphicon glyphicon-ok"></span></button>
            </span>
          </div><!-- /input-group -->
        </form>

        <ul class="list-inline social">
          <li><%= link_to image_tag( 'icn_gplus.gif'), "https://plus.google.com/107055844073909929988" , :rel => 'publisher', :target => "_blank" %></li>
          <li><%= link_to image_tag( 'icn_fb.gif'), 'https://www.facebook.com/paddlesportsnorthamerica', :target => "_blank" %></li>
        </ul>

        
      </div>

      <div class="col-md-6 sponsor-footer">
        <h4>Founding Sponsors</h4>
        <div class="row">
          <div class="col-md-4">
            <a href="http://wernerpaddles.com" target="_blank" title="Werner Paddles"><%= image_tag 'sponsor-werner-white-145.png' %></a>
          </div>

          <div class="col-md-4">
            <a href="http://www.phseakayaks.com/" target="_blank" title="PH Custom Sea Kayaks"><%= image_tag 'sponsor-ph-white-145.png' %></a>
          </div>

          <div class="col-md-4">
            <a href="http://www.atlantickayaktours.com/" target="_blank" title="Atlantic Kayak Tours"><%= image_tag 'sponsor-akt-white-145.png' %></a>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4  col-md-offset-2">
            <a href="http://www.seakayakinguk.com/" target="_blank" title="Sea Kayaking UK"><%= image_tag 'sponsor-skuk-white-145.png' %></a>
          </div>

          <div class="col-md-4">
            <a href="http://www.valleyseakayaks.com/" target="_blank" title="Valley Sea Kayaks"><%= image_tag 'sponsor-valley-white-145.png' %></a>
          </div>
        </div>

        <div class="row bc-footer">
          <div class="col-md-4">
            <a class="float-right" href="https://www.britishcanoeing.org.uk/" target="_blank"><%= image_tag 'bc_logo_white.png', :alt => 'British Canoeing', :title => 'British Canoeing', :class => 'img-responsive' %></a>
          </div>

          <div class="col-md-8">
            <p>Paddlesports North America is a British Canoeing Affiliated Organization and Coaching Delivery Center</p>
          </div>
        </div>
      </div>

      <div class="col-md-3" itemscope itemtype="http://schema.org/Organization">

        <h4>Contact Info</h4>
        <!-- <address itemprop="address">
          <strong itemprop="name">Paddlesports North America, <abbr title="Incorporated">Inc.</abbr></strong><br />
           1228 1/2 North Washington<br />
           Lansing Michigan, 48906<br />
        </address> -->
        <a href="tel:<%= t('pna.contact.phone.compact') %>"><%= t('pna.contact.phone.pna') %> &mdash; <em itemprop="telephone"><%= t('pna.contact.phone.plain') %></em></a>
        <address>
          <a href="mailto:<%= t('pna.contact.email') %>" itemprop="email"><%= t('pna.contact.email') %></a>
        </address>
      </div>
    </div>
  </div>
</footer>

<div class="subfooter">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <p>&copy; 2014 Paddlesports North America, Inc.</p>
        <p class="small">Paddlesports North America (PNA) is a not-for-profit, educational, public charity formed to deliver British Canoeing programs throughout North America. PNA is exempt from Federal income tax under section 501(c)3 of the Internal Revenue Code.</p>
      </div>
      <div class="col-md-2 text-right">
        <a href="http://www.guidestar.org/organizations/80-0962350/paddlesports-north-america.aspx" target="_blank"><img src="http://widgets.guidestar.org/gximage2?o=9334115&l=v4" /></a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Paddlesports North America" %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Paddlesports North America promotes paddler education, safety and stewardship of the environment throughout North America." %>">
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>

<!-- @TODO: Replace with a trimmed down version when we know what we need -->
<%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.js" %>

<%= csrf_meta_tags %>

<%= yield(:head) %>

<%= render 'layouts/og_meta' %>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    <% end %>

app/views/layouts/_navigation.html.erb
  <div class="navbar navbar-default navbar-main navbar-fixed-top" role="navigation">

    <div class="container navbar-util visible-md visible-lg">
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-globe"></span> Language</a></li>
        <li><a href="#">Log In</a></li>
        <li><a><span class="glyphicon glyphicon-search"></span></a>

        </li>
      </ul>-->
    </div>

    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only"><%= t('nav.toggle') %></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to image_tag(t('pna.logo'), :alt => t('pna.name'), :class => 'img-responsive'), root_path, :class => 'navbar-brand' %>
      </div>
      <div  class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= "active" if current_page?(controller: 'home', action: 'about') %>"><%= link_to t('nav.about'), '/about' %></li>
          <li class="<%= "active" if current_page?(controller: 'calendar', action: 'index') %>"><%= link_to t('nav.calendar'), calendar_path %></li>
          <li class="<%= "active" if current_page?(controller: 'coaches', action: 'index') %>"><%= link_to 'Coaches', '/coaches' %></li>
          <li class="<%= "active" if current_page?(controller: 'home', action: 'documents') %>"><%= link_to 'Documents', '/documents' %></li>
          <li class="<%= "active" if current_page?(controller: 'home', action: 'guidance') %>"><%= link_to 'Guidance', '/guidance' %></li>
          <li class="<%= "active" if current_page?(controller: 'home', action: 'membership') %>"><%= link_to t('nav.membership'), '/membership' %></li>
          <li class="<%= "active" if current_page?(controller: 'contact') %>"><%= link_to t('nav.contact'), '/contact' %></li>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/_og_meta.html.erb
<meta property="og:image" content="https://s3.amazonaws.com/paddlesportsnorthamerica/assets/pna-medalion.png" />
<meta property="og:title" content="Paddlesports North America" />
<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : "Paddlesports North America promotes paddler education, safety and stewardship of the environment throughout North America." %>" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render :partial => 'layouts/head' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>" data-spy="scroll" data-target=".scrollspy">

      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>


      <%= yield %>


      <%= render 'layouts/footer' %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-48709426-1', 'paddlesportsnorthamerica.org');
        ga('send', 'pageview');

      </script>
  </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render :partial => 'layouts/head' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>

      <%= yield %>


      <%= render 'layouts/footer' %>

      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-48709426-1', 'paddlesportsnorthamerica.org');
        ga('send', 'pageview');

      </script>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render :partial => 'layouts/head' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>" data-spy="scroll" data-target=".scrollspy">
      <div class="top-bar">
        <div class="container">
          <h1 class="logo"><span class="seo">Paddlesports North America</span></h1>
        </div>
      </div>
      <%= yield %>

      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-48709426-1', 'paddlesportsnorthamerica.org');
        ga('send', 'pageview');

      </script>
  </body>
</html>